version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/postgres:12.1-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: genetica
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: run tests
          command: python manage.py test


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test
